### ISSUE TITLE
Stuck on Assignment 01

### ISSUE THREAD

**Issue by spkvfx** [Media-Ed-Online/intro-web-dev-resources#2]
My moodle seems to be stuck on Week 01 with all additional weeks "not available". I wrote Justine a few days ago, but I have yet to get a response. I am assuming that this is a result of either the 404 issues mentioned earlier, or I failed to do something to trigger Week 02 to activate.

please advise.

**Comment by mabonmoon** [comment]
@spkvfx Me too - I am a little concerned, and was planning on writing an email today as well. I believe the instructors have to make the next week available, that is the way it is in my other online classes, so we just have to wait. The topics on the course website are at least available, so I think I am just going to go through those and hope week 2 opens up soon...?

**Comment by abaiady** [comment]
I'm also stuck on assignment 1. Week 2 hasn't opened for me either. I sent the professor an email a few days ago as well. Glad to know its not a problem only specific to me. If I get a reply I'll give an update to you here. For now, I think we just sit tight and wait until it unlocks for us.

**Comment by spkvfx** [comment]
Well, I am glad it's not just me or something that I neglected to do. I am guessing that the issue must be relating to the technical problems we were notified of earlier. Hopefully this will be resolved soon.

**Comment by JustineEvansUM** [comment]
Hey, gang! Please let me know if these problems persist!

**Comment by Sonnyboyrsamson** [comment]
So Ive been trying to upload assignment 1. Im getting a message in moodle saying 
Not available unless: You achieve a required score in Student Contract??? Not sure what this means! someone please help! Not sure if professor fixed this problem just yet

**Comment by JustineEvansUM** [comment]
Hey @Sonnyboyrsamson, no sweat! You just haven't filled out [the student contract](https://moodle.umt.edu/mod/questionnaire/view.php?id=1235501) yet, located in the introduction. Give that a go, and let me know! :)

**Comment by Sonnyboyrsamson** [comment]
It worked. Thx Professor

________________________________
