### ISSUE TITLE
issues with atom

### ISSUE THREAD

**Issue by Dbuerman** [Media-Ed-Online/intro-web-dev-resources#3]
i cant seem to get atom to load in my mac i tried restarting the browser and my computer and it just says that it is not responding at the moment i just wanted to know if anyone else is having this issue im currently trying to finish assignment 2

**Comment by JustineEvansUM** [comment]
Hey, @Dbuerman;

Does anything eventually improve if you "keep waiting?" (in Atom)

**Comment by Dbuerman** [comment]
It just keeps saying atom is not responding it froze my computer and i shut it down so ill have to restart it later and see if it works

**Comment by JustineEvansUM** [comment]
Huh. We can try uninstalling Atom and reinstalling, or using a different Editor. [Brackets](http://brackets.io/) and [Komodo](https://www.activestate.com/komodo-ide/downloads/edit) are great tools as well.

If you get to the stage, let me know so we can re-synch your files!
