### ISSUE TITLE
Modules and Topics unavailable still

### ISSUE THREAD

**Issue by XtianZoo** [Media-Ed-Online/intro-web-dev-resources#7]
I am still unable to open and view any of the modules and topics on either Moodle or the website.

**Comment by mafordah** [comment]
I'm in the same boat. I finished (or at least I thought I finished) everything in the introduction, but everything's still locked.

**Comment by tclark1178** [comment]
Same with me! although, maybe they won't be open till next week.

**Comment by mafordah** [comment]
@tclark1178  The class schedule has Assignment 1: Repositories due on Monday, but maybe that's when it opens instead?? I emailed our instructor about it yesterday. I'll let you guys know if I hear anything before she responds here.

**Comment by mafordah** [comment]
I got a response, and I was missing an answer to my student contract because of an update. She reopened it for me and I answered it, but I still don’t have access... maybe it just opens next week

**Comment by treshasanders** [comment]
I couldn't access it either, but the pages are in GitHub here: https://github.com/Media-Ed-Online/intro-web-dev/tree/gh-pages/_docs/topic-01

**Comment by treshasanders** [comment]
However, looking at the files in 04-github-site , they were last updated an hour ago (so around 6pm, Jan 20) and they do not contain any language. I assume that means the section has not been opened because the assignment itself is not complete. @JustineEvansUM can you confirm so we know we're not behind in the class?

**Comment by aprilmh** [comment]
So am I, have any of you had any luck getting into the next assignment?

**Comment by JustineEvansUM** [comment]
@treshasanders I can totally confirm! Everyone _should_ see the available assignment at this time. If not, please reach out!
