### ISSUE TITLE
Image link's broken

### ISSUE THREAD

**Issue by ashtonmwilson** [Media-Ed-Online/intro-web-dev-resources#9]
Can anyone tell me why my image links are broken?
[09 Live site](https://ashtonmwilson.github.io/web-dev-hw/assignment_09/)
I am linking in the same way as I did in previous assignments.
When I use the browser preview in atom, it works, what is different when it is in GIT?

**Comment by mafordah** [comment]
@ashtonmwilson I took a look at your code your image links are `<img src="images/bumper.png">` and `<img src="images/surf.png">` but your actual images are labeled "bumper.PNG" and "surf.PNG". I've had the extension case be an issue before when displaying images. Hopefully that helps!

**Comment by JustineEvansUM** [comment]
Hi, @ashtonmwilson;

@mafordah is right on the money! Thanks!

If you change either you code to `.PNG` _or_ rename your files with lowercase `.png` it will work. Here it is with changing your URLs to captial `.PNG`:
<img width="1110" alt="wilson" src="https://user-images.githubusercontent.com/25491569/55696796-d15ea100-597b-11e9-9c16-69aa981bdd57.png">

PS - Looks great!

**Comment by ashtonmwilson** [comment]
ahhh snap. What a dangus move! Thanks for the help, and positive feed back!
